name: Run Terraform for Services

on:
  push:
    paths:
      - 'services/**'
  pull_request:
    paths:
      - 'services/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Iterate through subdirectories and run Terraform
        run: |
          find services -mindepth 1 -maxdepth 1 -type d | while read dir; do
            echo "Processing $dir"
            cd "$dir"
            terraform init
            terraform plan -no-color -input=false -out=tfplan
            terraform apply -no-color -input=false tfplan
            cd - > /dev/null
          done